// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: WordCount.proto

package Service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetWordCountClient is the client API for GetWordCount service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetWordCountClient interface {
	WordCount(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type getWordCountClient struct {
	cc grpc.ClientConnInterface
}

func NewGetWordCountClient(cc grpc.ClientConnInterface) GetWordCountClient {
	return &getWordCountClient{cc}
}

func (c *getWordCountClient) WordCount(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Service.GetWordCount/WordCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetWordCountServer is the server API for GetWordCount service.
// All implementations must embed UnimplementedGetWordCountServer
// for forward compatibility
type GetWordCountServer interface {
	WordCount(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedGetWordCountServer()
}

// UnimplementedGetWordCountServer must be embedded to have forward compatible implementations.
type UnimplementedGetWordCountServer struct {
}

func (UnimplementedGetWordCountServer) WordCount(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WordCount not implemented")
}
func (UnimplementedGetWordCountServer) mustEmbedUnimplementedGetWordCountServer() {}

// UnsafeGetWordCountServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetWordCountServer will
// result in compilation errors.
type UnsafeGetWordCountServer interface {
	mustEmbedUnimplementedGetWordCountServer()
}

func RegisterGetWordCountServer(s grpc.ServiceRegistrar, srv GetWordCountServer) {
	s.RegisterService(&GetWordCount_ServiceDesc, srv)
}

func _GetWordCount_WordCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetWordCountServer).WordCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Service.GetWordCount/WordCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetWordCountServer).WordCount(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// GetWordCount_ServiceDesc is the grpc.ServiceDesc for GetWordCount service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetWordCount_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Service.GetWordCount",
	HandlerType: (*GetWordCountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WordCount",
			Handler:    _GetWordCount_WordCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "WordCount.proto",
}
